// Run through playwright-cli run-code against a dedicated QA profile.
async (page) => {
  const assert = (condition, message) => { if (!condition) throw Error(message); };
  const language = page.locator('#ui-language');
  const fixturePath = await page.evaluate(async () => {
    const state = await (await fetch('/api/state')).json();
    return state.data_dir.replace(/[\\/][^\\/]+$/, '') + '/i18n-fixtures';
  });
  const closeSettings = page.locator('#settings-dialog .close-dialog');
  if(await page.locator('#prompt-dialog').isVisible()) await page.locator('#prompt-dialog .close-dialog').click();
  if(!await page.locator('#settings-dialog').isVisible()) await page.locator('#open-settings').click();
  const waitLanguage = async value => {
    await Promise.all([page.waitForResponse(response => response.url().endsWith('/api/ui-language') && response.ok()), language.selectOption(value)]);
    await page.waitForFunction(value => document.documentElement.lang === value, value);
    await page.waitForFunction(() => document.querySelector('#settings-message').textContent.length > 0);
  };
  await waitLanguage('en');
  await page.locator('#save-settings').click();
  const detail = page.locator('[data-attribute=identity]');
  await detail.uncheck();
  await page.locator('[data-attribute=background]').uncheck();
  await page.locator('#preview-prompt').click();
  await page.locator('#prompt-dialog').waitFor({state:'visible'});
  const prompt = await page.locator('#prompt-text').textContent();
  assert(prompt.includes('LEARN_WITH_LORA — DO NOT DESCRIBE: stable visual identity'), 'Unchecked identity must be omitted');
  assert(prompt.includes('CONTROL_WITH_PROMPT — DESCRIBE IF VISIBLE: clothing'), 'Checked clothing must be described');
  await page.locator('#prompt-dialog .close-dialog').click();
  await page.locator('#open-path').click();
  await page.locator('#folder-path').fill(fixturePath);
  await page.locator('#import-path').click();
  await page.waitForFunction(() => document.querySelectorAll('.image-card').length === 2);
  const editor = page.locator('#caption-editor');
  const caption = 'Clothing, Saved, Waiting. This user text must stay unchanged.';
  await editor.fill(caption);
  await page.locator('#open-settings').click();
  await page.locator('[name=local_source]').selectOption('external');
  await page.locator('[name=local_url]').fill('http://127.0.0.1:12345/v1');
  await page.locator('#local-api-key').fill('qa-draft-key-not-to-save');
  await waitLanguage('cs');
  assert(await editor.inputValue() === caption, 'Switch must preserve unsaved caption');
  assert(await page.locator('[name=local_url]').inputValue() === 'http://127.0.0.1:12345/v1', 'Switch must preserve setup draft');
  assert(await page.locator('#local-api-key').inputValue() === 'qa-draft-key-not-to-save', 'Switch must preserve key draft');
  assert(await page.locator('[name=language]').inputValue() === 'English', 'Caption language must not change');
  assert(!await detail.isChecked(), 'Switch must preserve omitted identity');
  assert(await page.locator('[data-attribute=clothing]').isChecked(), 'Switch must preserve included clothing');
  assert(!(await page.locator('#local-discovery-message').textContent()).startsWith('Check common'), 'Dynamic setup help must translate');
  await waitLanguage('en');
  assert((await page.locator('#local-discovery-message').textContent()).startsWith('Check common'), 'Dynamic setup help must translate back');
  await waitLanguage('cs');
  await closeSettings.click();
  await page.locator('#save-caption').click();
  await page.locator('#pick-folder').click();
  await page.waitForFunction(() => !document.querySelector('#use-folder').disabled);
  assert(await page.locator('#folder-grid img').count() === 2, 'Folder must show thumbnails');
  assert(await page.locator('.tree-row.selected').count() === 1, 'Selected folder styling must survive localization');
  await page.locator('#browse-path').fill(fixturePath + '/Waiting.png');
  await page.locator('#folder-go').click();
  await page.locator('#folder-error').waitFor({state:'visible'});
  assert(!(await page.locator('#folder-error').textContent()).includes('folder.'), 'Folder error must translate');
  await page.locator('#folder-dialog .close-dialog').click();
  await page.locator('[name=output_format]').selectOption('bria_json');
  assert(await page.locator('[name=words]').isDisabled(), 'JSON must not use word target');
  assert(await page.locator('#json-format-note').isVisible(), 'JSON explanation must be visible');
  assert(!(await page.locator('#json-format-note').textContent()).startsWith('FIBO JSON uses'), 'JSON explanation must translate');
  await page.locator('#preview-prompt').click();
  await page.locator('#prompt-dialog').waitFor({state:'visible'});
  const jsonPrompt=await page.locator('#prompt-text').textContent();
  assert(jsonPrompt.includes('short_description') && jsonPrompt.includes('No total word-count constraint applies'), 'FIBO schema must remain intact');
  await page.locator('#prompt-dialog .close-dialog').click();
  await page.locator('#open-settings').click();
  await waitLanguage('en');
  await closeSettings.click();
  await page.locator('[name=output_format]').selectOption('normal');
  await page.waitForFunction(() => document.querySelector('#recipe-status').textContent === 'Settings saved');
  await page.reload();
  await page.waitForFunction(() => document.documentElement.lang === 'en' && document.querySelectorAll('.image-card').length === 2);
  assert(await editor.inputValue() === caption, 'Saved caption must round-trip without translation');
  assert(!await detail.isChecked(), 'Omitted identity must persist after reload');
  assert(await page.locator('.training-limit').count() === 0, 'Removed caveat must not exist');
  await page.locator('.recipe').evaluate(element => element.scrollTop = 620);
  await page.screenshot({path:'output/playwright/localization-en.png'});
  await page.locator('#open-settings').click();
  await waitLanguage('cs');
  await closeSettings.click();
  await page.locator('.recipe').evaluate(element => element.scrollTop = 620);
  await page.screenshot({path:'output/playwright/localization-cs.png'});
  console.log(JSON.stringify({languages:true, draft_preservation:true, checkbox_semantics:true, persistence:true, folder_navigation:true, json_prompt:true}));
}
